version: '3.7'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    entrypoint: ./entrypoint.sh
    ports:
      - 8888:3000
    volumes:
      - ./frontend-data:/etc/frontend-data
    networks:
      netmicroservice:
        ipv4_address: 10.9.0.10

  graphql:
    build:
      context: ./GraphQL
      dockerfile: Dockerfile
    container_name: graphql-microservice
    restart: always
    entrypoint: ./entrypoint.sh
    environment:
      USER_MICROSERVICE_ADDR: http://10.9.0.40:8000
      BUY_MICROSERVICE_ADDR: http://10.9.0.40:8000
      PRODUCT_MICROSERVICE_ADDR: http://10.9.0.30:7000
      MONGODB_URI: mongodb://gonzalo:12345@10.9.0.100:27017/gonzaloShop
      TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzMjYxNjFmZTZlZTgwYmM5ZjNjNDlkOSIsImlhdCI6MTY2MzUxOTg3Nn0.QIyMubnQuAkCeseIbvq2S1n06Pr1gFtQbsfh7ZaGEk0
    expose: 
        - "4000"
    ports:
      - 4500:4000
    volumes:
      - ./graphql-data:/etc/microservice-data
    networks:
      netmicroservice:
        ipv4_address: 10.9.0.20


  product-microservice:
    build:
      context: ./JavaScript
      dockerfile: Dockerfile
    container_name: product-microservice
    restart: always
    entrypoint: ./entrypoint.sh
    environment:
      PORT: 7000
      MYSQL_ADDR: 10.9.0.200
      MYSQL_PORT: 3306
      MONGODB_URI: mongodb://gonzalo:12345@10.9.0.100:27017/gonzaloShop
      TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzMjYxNjFmZTZlZTgwYmM5ZjNjNDlkOSIsImlhdCI6MTY2MzUxOTg3Nn0.QIyMubnQuAkCeseIbvq2S1n06Pr1gFtQbsfh7ZaGEk0
    expose: 
        - "7000"
    ports:
      - 7500:7000
    volumes:
      - ./javascript-data:/etc/microservice-data
    networks:
      netmicroservice:
        ipv4_address: 10.9.0.30

  user-microservice:
    build:
      context: ./Python
      dockerfile: Dockerfile
    container_name: user-microservice
    restart: always
    entrypoint: ./entrypoint.sh
    environment:
      PORT: 7000
      MYSQL_ADDR: 10.9.0.200
      MYSQL_PORT: 3306
      MONGODB_URI: mongodb://gonzalo:12345@10.9.0.100:27017/gonzaloShop
      TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzMjYxNjFmZTZlZTgwYmM5ZjNjNDlkOSIsImlhdCI6MTY2MzUxOTg3Nn0.QIyMubnQuAkCeseIbvq2S1n06Pr1gFtQbsfh7ZaGEk0
    expose: 
        - "8000"
    ports:
      - 3530:8000
    volumes:
      - ./python-data:/etc/microservice-data
    networks:
      netmicroservice:
        ipv4_address: 10.9.0.40

  buy-microservice:
    build:
      context: ./PHP
      dockerfile: Dockerfile
    container_name: buy-microservice
    restart: always
    entrypoint: ./entrypoint.sh
    environment:
      APP_NAME: Laravel
      APP_ENV: production
      APP_KEY: "base64:Fqma3thiJ6QUgVocnnzSVqwFaHfKzA5AWoUW/umLGSA:" 
      APP_DEBUG: false
      APP_URL: http://localhost
      LOG_CHANNEL: stack
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: 10.9.0.200
      DB_PORT: 3306
      DB_DATABASE: db_gonzaloshop
      DB_USERNAME: root
      DB_PASSWORD: 12345
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      MEMCACHED_HOST: 127.0.0.1
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: "${APP_NAME}"
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: 
      AWS_USE_PATH_STYLE_ENDPOINT: false
      PUSHER_APP_ID: 
      PUSHER_APP_KEY: 
      PUSHER_APP_SECRET: 
      PUSHER_HOST: 
      PUSHER_PORT: 443
      PUSHER_SCHEME: https
      PUSHER_APP_CLUSTER: mt1
      VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
      VITE_PUSHER_HOST: "${PUSHER_HOST}"
      VITE_PUSHER_PORT: "${PUSHER_PORT}"
      VITE_PUSHER_SCHEME: "${PUSHER_SCHEME}"
      VITE_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
    expose: 
        - "3000"
    ports:
      - 3550:3000
    volumes:
      - ./php-data:/etc/microservice-data
    networks:
      netmicroservice:
        ipv4_address: 10.9.0.50


  mongodb:
    build:
      context: ./MongoDB
      dockerfile: Dockerfile
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_USERNAME: usermongo
      MONGO_INITDB_PASSWORD: 12345
      MONGO_INITDB_DATABASE: gonzaloshop
    ports:
      - 12500:27017
    volumes:
      - ./mongo:/etc/mongo
    networks:
      netmicroservice:
        ipv4_address: 10.9.0.100


  mysql:
    build:
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_gonzaloshop
      MYSQL_USER: userdb
      MYSQL_PASSWORD: "12345"
    ports:
      - 23306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./schemas:/var/lib/mysql
    networks:
      netmicroservice:
        ipv4_address: 10.9.0.200


networks:
    netmicroservice:
      ipam:
        driver: default
        config:
          - subnet: 10.9.0.0/24

volumes:
  graphql: {}
  mongo: {}
  schemas: {}
  frontend: {}
  product-microservice: {}
  user-microservice: {}
  buy-microservice: {}