version: '3.7'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    entrypoint: ./entrypoint.sh
    ports:
      - 8888:3000
    volumes:
      - ./frontend-data:/etc/frontend-data
    networks:
      netmicroservice:
        ipv4_address: 10.9.0.10

  graphql:
    build:
      context: ./GraphQL
      dockerfile: Dockerfile
    container_name: graphql-microservice
    restart: always
    entrypoint: ./entrypoint.sh
    environment:
      PORT: 7000
      MYSQL_ADDR: 10.9.0.200
      MYSQL_PORT: 3306
      MONGODB_URI: mongodb://gonzalo:12345@10.9.0.100:27017/gonzaloShop
      TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzMjYxNjFmZTZlZTgwYmM5ZjNjNDlkOSIsImlhdCI6MTY2MzUxOTg3Nn0.QIyMubnQuAkCeseIbvq2S1n06Pr1gFtQbsfh7ZaGEk0
    ports:
      - 4500:4000
    volumes:
      - ./graphql-data:/etc/microservice-data
    networks:
      netmicroservice:
        ipv4_address: 10.9.0.20


  product-microservice:
    build:
      context: ./JavaScript
      dockerfile: Dockerfile
    container_name: product-microservice
    restart: always
    entrypoint: ./entrypoint.sh
    environment:
      PORT: 7000
      MYSQL_ADDR: 10.9.0.200
      MYSQL_PORT: 3306
      MONGODB_URI: mongodb://gonzalo:12345@10.9.0.100:27017/gonzaloShop
      TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzMjYxNjFmZTZlZTgwYmM5ZjNjNDlkOSIsImlhdCI6MTY2MzUxOTg3Nn0.QIyMubnQuAkCeseIbvq2S1n06Pr1gFtQbsfh7ZaGEk0
    ports:
      - 7500:7000
    volumes:
      - ./javascript-data:/etc/microservice-data
    networks:
      netmicroservice:
        ipv4_address: 10.9.0.30

  user-microservice:
    build:
      context: ./Python
      dockerfile: Dockerfile
    container_name: user-microservice
    restart: always
    entrypoint: ./entrypoint.sh
    environment:
      PORT: 7000
      MYSQL_ADDR: 10.9.0.200
      MYSQL_PORT: 3306
      MONGODB_URI: mongodb://gonzalo:12345@10.9.0.100:27017/gonzaloShop
      TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzMjYxNjFmZTZlZTgwYmM5ZjNjNDlkOSIsImlhdCI6MTY2MzUxOTg3Nn0.QIyMubnQuAkCeseIbvq2S1n06Pr1gFtQbsfh7ZaGEk0
    ports:
      - 8500:8000
    volumes:
      - ./python-data:/etc/microservice-data
    networks:
      netmicroservice:
        ipv4_address: 10.9.0.40


  mongodb:
    build:
      context: ./MongoDB
      dockerfile: Dockerfile
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_USERNAME: usermongo
      MONGO_INITDB_PASSWORD: 12345
      MONGO_INITDB_DATABASE: gonzaloshop
    ports:
      - 12500:27017
    volumes:
      - ./mongo:/etc/mongo
    networks:
      netmicroservice:
        ipv4_address: 10.9.0.100


  mysql:
    build:
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_gonzaloshop
      MYSQL_USER: userdb
      MYSQL_PASSWORD: "12345"
    ports:
      - 23306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./schemas:/var/lib/mysql
    networks:
      netmicroservice:
        ipv4_address: 10.9.0.200


networks:
    netmicroservice:
      ipam:
        driver: default
        config:
          - subnet: 10.9.0.0/24

volumes:
  graphql: {}
  mongo: {}
  schemas: {}
  frontend: {}
  product-microservice: {}
  user-microservice: {}